version: "3.9"

services:
  pg_s3_backup:
    build: .
    environment:
      URLS: "postgres://user:password@host:port/dbname"
      S3_ENDPOINT: "your_s3_endpoint"
      S3_BUCKET: "your_s3_bucket"
      S3_ACCESS_KEY: "your_s3_access_key"
      S3_SECRET_KEY: "your_s3_secret_key"
      INTERVAL: "24h"
